"""Add login tracking fields to User with server_default

Revision ID: a036a50800b6
Revises: b15a17156fa5
Create Date: 2026-07-22 17:43:17.543802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a036a50800b6'
down_revision = 'b15a17156fa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_login')
        batch_op.drop_column('login_count')

    # ### end Alembic commands ###
