"""add location fields to user

Revision ID: c26b28267fa6
Revises: a036a50800b6
Create Date: 2026-07-27 22:38:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c26b28267fa6'
down_revision = 'a036a50800b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_location', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('preferred_location', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('preferred_location')
        batch_op.drop_column('allow_location')

    # ### end Alembic commands ###
